serverless:
  Resources:
    SendPushNotificationFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: lambda/api-internal/sendPushNotification.handlerImplementation
        Runtime: nodejs20.x
        CodeUri: .
        Environment:
          Variables:
            REDIS_ENDPOINT:
            REDIS_PORT:
            COGNITO_USER_POOL_ID:
            COGNITO_CLIENT_ID:
        Events:
          SendPushNotificationApi:
            Type: Api
            Properties:
              Path: /student/internal/push-notification
              Method: post

openapi:
  paths:
    /student/internal/push-notification:
      post:
        summary: Send a push notification to a device
        description: Sends a push notification to a device using the push token.
        parameters:
          - name: Authorization
            in: header
            required: true
            description: Bearer token (access token or refresh token) for authentication.
            schema:
              type: string
        requestBody:
          description: The push notification payload.
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  recipients:
                    type: array
                    description: The recipients to get notifications.
                    items:
                      type: string
                      description: An ID token for a recipient.
                  notification:
                    type: object
                    description: The notification data.
                    properties:
                      title:
                        type: string
                        description: The title of the notification.
                      body:
                        type: string
                        description: The body of the notification.
                      data:
                        type: object
                        required: false
                        description: The data to send with the notification.
        responses:
          '200':
            description: Push notification sent successfully
          '400':
            description: Bad request - missing or invalid parameters
          '500':
            description: Internal server error