serverless:
  Resources:
    SendPushNotificationFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: lambda/sendPushNotification/sendPushNotification.handlerImplementation
        Runtime: nodejs20.x
        CodeUri: .
        Environment:
          Variables:
            REDIS_ENDPOINT:
            REDIS_PORT:
            COGNITO_USER_POOL_ID:
            COGNITO_CLIENT_ID:
        Events:
          SendPushNotificationApi:
            Type: Api
            Properties:
              Path: /student/internal/push-notification
              Method: post

openapi:
  paths:
    /student/internal/push-notification:
      post:
        summary: Send a push notification to a device
        description: Sends a push notification to a device using the push token.
        parameters:
          - name: Authorization
            in: header
            required: true
            description: Bearer token (access token or refresh token) for authentication.
            schema:
              type: string
        responses:
          '200':
            description: Push notification sent successfully
          '400':
            description: Bad request - missing or invalid parameters
          '500':
            description: Internal server error