serverless:
  AuthenticateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambda/authenticateUser.handler
      Runtime: nodejs20.x
      CodeUri: .
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: us-west-2_Onci94rlj
      Events:
        AuthenticateUser:
          Type: Api
          Properties:
            Path: /student/authenticate
            Method: post

openapi:
  paths:
    /student/authenticate:
      post:
        summary: Authenticate Student
        description: Authenticates a student using an access token and returns the registered username and email.
        parameters:
          - name: Authorization
            in: header
            required: true
            description: The Bearer token (access token) for the student.
            schema:
              type: string
        responses:
          '200':
            description: Student successfully authenticated and details returned
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      type: string
                      description: The username of the student.
                    email:
                      type: string
                      description: The email address of the student.
                    schoolKey:
                      type: string
                      description: The unique key of the student's school.
          '400':
            description: Bad request - missing or invalid access token
          '401':
            description: Unauthorized - invalid or expired access token
          '500':
            description: Internal server error