serverless:
  Resources:
    UserRegistrationFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: lambda/userRegistration.handlerImplementation
        Runtime: nodejs20.x
        CodeUri: .
        Environment:
          Variables:
            REDIS_ENDPOINT:
            REDIS_PORT:
            COGNITO_USER_POOL_ID:
            COGNITO_CLIENT_ID:
        Events:
          UserRegistration:
            Type: Api
            Properties:
              Path: /student/register
              Method: post

openapi:
  paths:
    /student/register:
      post:
        summary: Register a student
        description: Registers a student after email verification and returns authentication tokens.
        parameters:
          - name: email
            in: query
            required: true
            description: The email address of the student.
            schema:
              type: string
          - name: authToken
            in: query
            required: true
            description: The authorization token received after email verification.
            schema:
              type: string
        requestBody:
          description: The username and password for student registration.
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    description: The desired username for the new student.
                  password:
                    type: string
                    description: The desired password for the new student.
                required:
                  - username
                  - password
        responses:
          '200':
            description: Student successfully registered and tokens returned.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "User successfully created"
                    accessToken:
                      type: string
                      description: Access token for API authorization.
                    idToken:
                      type: string
                      description: ID token for user identification.
                    refreshToken:
                      type: string
                      description: Token used to refresh the access token.
          '400':
            description: Bad request - missing or invalid parameters.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Email and authorization token are required"
          '401':
            description: Unauthorized - Invalid or expired authorization token.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Invalid or expired authorization token"
          '409':
            description: Conflict - User already exists.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "User already exists with the provided email"
          '500':
            description: Internal server error.
