AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 512  # Default memory size in MB
    Timeout: 15  # Default timeout in seconds 

Resources: {}