serverless:
  Resources:
    VerifyEmailCompleteFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: lambda/api/emailVerificationComplete.handlerImplementation
        Runtime: nodejs20.x
        CodeUri: .
        Environment:
          Variables:
            REDIS_ENDPOINT:
            REDIS_PORT:
        Events:
          VerifyEmailComplete:
            Type: Api
            Properties:
              Path: /student/verify-email/complete
              Method: post

openapi:
  paths:
    /student/verify-email/complete:
      post:
        summary: Complete email verification
        description: Validates the verification code sent to the student's email and returns an authorization token if successful.
        parameters:
          - name: email
            in: query
            required: true
            description: The email address of the student to verify.
            schema:
              type: string
          - name: verificationCode
            in: query
            required: true
            description: The 6-digit verification code sent to the email.
            schema:
              type: string
        responses:
          '200':
            description: Email verified successfully and an authorization token returned
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Email verified successfully."
                    authToken:
                      type: string
                      description: Authorization token for further authentication
                      example: "eyJhbGciOiJIUzI1NiIsInR5..."
          '400':
            description: Bad request - missing or invalid parameters
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Email and verification code are required"
          '401':
            description: Invalid or expired verification code
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Invalid verification code"
          '500':
            description: Internal server error
