name: Deploy (Staging)

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true  # Only run if the PR is merged
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Build the project
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: CDK Bootstrap
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace @student-manager/cdk bootstrap

      - name: CDK Deploy
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace @student-manager/cdk deploy
